//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS_WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public string ID { get; set; }
        public string Market { get; set; }
        public string Collection { get; set; }
        public string Route { get; set; }
    }
}
